repos:
  # Sort import
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Format code
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  # Delete useless imports
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--recursive", "--in-place", "--remove-unused-variables"]
